server:
  port: 8085

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    url: jdbc:postgresql://payment-db:5432/payment_db
    username: payment_user
    password: payment_pass
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
