server:
  port: 8086

spring:
  application:
    name: ridematch-service
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    url: jdbc:postgresql://ridematch-db:5432/ridematch_db
    username: ridematch_user
    password: ridematch_pass
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
